apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googleclothes:d566a0dda63a455cfed0a21bc99a1baaebcadf92
        ports:
        - containerPort: 80
