apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googleclothes:8e62291e0d9909760a2ffe2e3c16c4ab7dee2f88
        ports:
        - containerPort: 80
