apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googleclothes:1aa3cb1bb27f9ac79147c3f3c79b3c907fc3b80b
        ports:
        - containerPort: 80
