apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-earphones:b1e65f0f0e7220391cceaded7073583459c23958
        ports:
        - containerPort: 80
