apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-earphones:d566a0dda63a455cfed0a21bc99a1baaebcadf92
        ports:
        - containerPort: 80
