apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-earphones:513c177b7ff8e90eceea7b3a0f3bf25bfed5ebb8
        ports:
        - containerPort: 80
