apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-backend:f97e85cf5a986da6e0af5f71dfdc510dfd6f7a40
          ports:
            - containerPort: 5000
