apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-backend:8e62291e0d9909760a2ffe2e3c16c4ab7dee2f88
          ports:
            - containerPort: 5000
