apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-electronics:b1e65f0f0e7220391cceaded7073583459c23958
        ports:
        - containerPort: 80
