apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-electronics:c0c203d4aa0741b3b2da15a0307c6d727c6f95fd
        ports:
        - containerPort: 80
