apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-main:9494773bd5713f7c809bf0da6868948f76fd1c34
        ports:
        - containerPort: 80

