apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-computers:8e62291e0d9909760a2ffe2e3c16c4ab7dee2f88
        ports:
        - containerPort: 80
