apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-computers:d566a0dda63a455cfed0a21bc99a1baaebcadf92
        ports:
        - containerPort: 80
