apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlepay:6097d417e56f1577e06cbb48cc84bb4516addd40
        ports:
        - containerPort: 80
