apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlepay:b1e65f0f0e7220391cceaded7073583459c23958
        ports:
        - containerPort: 80
