apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlepay:8e62291e0d9909760a2ffe2e3c16c4ab7dee2f88
        ports:
        - containerPort: 80
