apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-phones:b1e65f0f0e7220391cceaded7073583459c23958
        ports:
        - containerPort: 80
