apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-phones:8e62291e0d9909760a2ffe2e3c16c4ab7dee2f88
        ports:
        - containerPort: 80
