apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 744420879952.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-phones:513c177b7ff8e90eceea7b3a0f3bf25bfed5ebb8
        ports:
        - containerPort: 80
