apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlegrocery:9494773bd5713f7c809bf0da6868948f76fd1c34
        ports:
        - containerPort: 80
