apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlegrocery:8e62291e0d9909760a2ffe2e3c16c4ab7dee2f88
        ports:
        - containerPort: 80
