apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 066380524960.dkr.ecr.eu-north-1.amazonaws.com/shopping-site-googlegrocery:b1e65f0f0e7220391cceaded7073583459c23958
        ports:
        - containerPort: 80
